// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RevitAddinExtension;

internal sealed partial class Vsix
{
    public const string Id = "RevitAddinExtension.85b74bd0-c5af-4fa5-9728-4c2663fa325d";
    public const string Name = "RevitAddinExtension";
    public const string Description = @"Empty VSIX Project.";
    public const string Language = "en-US";
    public const string Version = "1.0";
    public const string Author = "Company";
    public const string Tags = "";
}
