// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------

using System;

namespace RevitAddinExtension;
/// <summary>
/// Helper class that exposes all GUIDs used across VS Package.
/// </summary>
internal sealed partial class PackageGuids
{
    public const string RevitAddinExtensionString = "2c6d31ab-750d-4722-a6ee-06f7ab0febaa";
    public static Guid RevitAddinExtension = new Guid(RevitAddinExtensionString);
}
/// <summary>
/// Helper class that encapsulates all CommandIDs uses across VS Package.
/// </summary>
internal sealed partial class PackageIds
{
    public const int MyCommand = 0x0100;
}