// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RevitExtension;

internal sealed partial class Vsix
{
    public const string Id = "RevitExtension.465bfade-bc3f-4e40-81be-7429e936282f";
    public const string Name = "RevitExtension";
    public const string Description = @"Empty VSIX Project.";
    public const string Language = "en-US";
    public const string Version = "1.0";
    public const string Author = "Company";
    public const string Tags = "";
}
